<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. Data Training, seperti namanya, data yang digunakan untuk training model. Sejauh ini kita telah melakukan tersebut. Data Validation, digunakan untuk proses validasi model dan mencegah overfitting. Data Testing, digunakan untuk testing model, sebagai simulasi penggunaan model pada dunia nyata. Data testing tidak boleh pernah dilihat oleh model sebelumnya.
2. Untuk mengukur kinerja model yang telah dibuat, performance metrics populer yang umum dan sering digunakan: accuracy, precission, dan recall. Accuracy menggambarkan seberapa akurat model dapat mengklasifikasikan dengan benar. Maka, accuracy merupakan rasio prediksi benar (positif dan negatif) dengan keseluruhan data. Dengan kata lain, accuracy merupakan tingkat kedekatan nilai prediksi dengan nilai aktual (sebenarnya). Nilai accuracy dapat diperoleh dengan persamaan (1). Precision menggambarkan tingkat keakuratan antara data yang diminta dengan hasil prediksi yang diberikan oleh model. Maka, precision merupakan rasio prediksi benar positif dibandingkan dengan keseluruhan hasil yang diprediksi positf. Dari semua kelas positif yang telah di prediksi dengan benar, berapa banyak data yang benar-benar positif. Nilai precision dapat diperoleh dengan persamaan (2). Recall menggambarkan keberhasilan model dalam menemukan kembali sebuah informasi. Maka, recall merupakan rasio prediksi benar positif dibandingkan dengan keseluruhan data yang benar positif. Nilai recall dapat diperoleh dengan persamaan (3).
3. Confusion matrix juga sering disebut error matrix. Pada dasarnya confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui.
4. Classification report digunakan untuk mengukur kualitas prediksi dari algoritma classification. Berapa banyak prediksi yang True dan berapa banyak yang False. Lebih khusus lagi, True Positive, False Positive, True negative dan False Negatives digunakan untuk memprediksi metrik classification report.

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [42]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [43]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [44]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [45]:
# Code here
from sklearn.preprocessing import scale

x = df.drop('survival_status',axis=1)
y = df['survival_status']

In [46]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix,classification_report, roc_auc_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, stratify=y, random_state=21)
model_knn = KNeighborsClassifier(n_neighbors=2)
model_knn.fit(x_train,y_train)

#Cross val score
cv = cross_val_score(model_knn, x, y, cv=10, scoring='roc_auc')
display(cv.mean())

0.6182751427316645

In [48]:
#predict data test
y_predict = model_knn.predict(x_test)

score = accuracy_score(y_test,y_predict)

In [49]:
score

0.7272727272727273

In [50]:
#confussion matrix
confusion_matrix(y_test,y_predict)

array([[50,  7],
       [14,  6]], dtype=int64)

In [51]:
#confussion matrix
confusion_matrix(y_test,y_predict, labels=[2,1]) #<- label positif, negatif

array([[ 6, 14],
       [ 7, 50]], dtype=int64)

In [52]:
TP = 6
FN = 14
FP = 7
TN = 50

In [53]:
#classification report
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           1       0.78      0.88      0.83        57
           2       0.46      0.30      0.36        20

    accuracy                           0.73        77
   macro avg       0.62      0.59      0.60        77
weighted avg       0.70      0.73      0.71        77



In [54]:
#menghitung nilai presisi, recall, f1-score dari model kita dalam memprediksi data yang positif
precision = TP/(TP+FP)
print(precision)

0.46153846153846156


In [55]:
recall = TP/(TP+FN)
print(recall)

0.3


In [56]:
f1score = 2*precision*recall/(precision+recall)
print(f1score)

0.3636363636363637


In [57]:
#menghitung nilai presisi, recall, f1-score dari model kita dalam memprediksi data yang negatif
precision1 = TN/(TN+FN)
print(precision1)

0.78125


In [58]:
recall1 = TN/(TN+FP)
print(recall1)

0.8771929824561403


In [59]:
f1score1 = 2*precision1*recall1/(precision1+recall1)
print(f1score1)

0.8264462809917354


---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:
1. Bias adalah perbedaan antara rata rata hasil prediksi dari model ML yang kita develop dengan data nilai yang sebenarnya. Bias yang tinggi dikarenakan dalam pembangunan model ML, dilakukan terlalu sederhan (oversimplified). Faktor penyebab lain dikarenakan model ML yang di develop terlalu tidak terlalu berinteraksi dengan training data. Variance adalah variabel dari prediksi model untuk data tertentu dimana memberikan kita informasi perserbaran data kita. Model yang memiliki variance tinggi sangat memperhatikan hanya pada train data. High variance model, perform baik di train data. Tetapi jika disuguhkan data baru yang belum pernah ditemukan di train data. Model tersebut tidak dapat mengeneralisasikan secara baik dari identifikasi data baru tersebut. 
2. Underfitting terjadi ketika model tidak bisa melihat logika dibelakang data, hingga tidak bisa melakukan prediksi dengan tepat, baik untuk dataset training maupun dataset lain yang serupa. Underfitting model akan memiliki high loss dan akurasi rendah. Overfitting terjadi karena model yang dibuat terlalu fokus pada training dataset tertentu, hingga tidak bisa melakukan prediksi dengan tepat jika diberikan dataset lain yang serupa. Overfitting biasanya akan menangkap data noise yang seharusnya diabaikan. Overfitting model akan memiliki low loss dan akurasi rendah.
3. Kompleksitas dari model ditentukan oleh Bias error, variance error, high variance, high bias dan error total. Bias error disebabkan oleh model yang terlalu simple. Variance error disebabkan oleh model yang terlalu kompleks. High bias yaitu error di data training dan validasi besar. High variance yaitu error di data training kecil dan di validasinya kecil ataupun sebaliknya.
4. Model yang baik merupakan model yang memiliki bias error dan variance error yang kecil
5. GridSearchcv digunakan saat akan mencoba semua hyperparameter yang mungkin dan RandomizedSearchCV digunakan saat memilih hyperparameter beberapa saja secara random

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [61]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [62]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [83]:
x = df.drop('survival_status',axis=1)
y = df['survival_status']

In [93]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

model = KNeighborsClassifier()
param_grid = {
    'n_neighbors' : np.arange(5,50),
    'weights' : ['distance','uniform']
}
gscv = GridSearchCV(model, param_grid=param_grid, cv=5, scoring='roc_auc')
gscv.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'weights': ['distance', 'uniform']},
             scoring='roc_auc')

In [94]:
gscv.best_params_

{'n_neighbors': 40, 'weights': 'uniform'}

In [95]:
gscv.best_score_

0.7151062091503269

In [108]:
gscv.predict_proba(x_test)

array([[0.725, 0.275],
       [0.725, 0.275],
       [0.65 , 0.35 ],
       [0.5  , 0.5  ],
       [0.7  , 0.3  ],
       [0.825, 0.175],
       [0.8  , 0.2  ],
       [0.8  , 0.2  ],
       [0.75 , 0.25 ],
       [0.7  , 0.3  ],
       [0.375, 0.625],
       [0.875, 0.125],
       [0.75 , 0.25 ],
       [0.85 , 0.15 ],
       [0.85 , 0.15 ],
       [0.925, 0.075],
       [0.8  , 0.2  ],
       [0.75 , 0.25 ],
       [0.775, 0.225],
       [0.475, 0.525],
       [0.875, 0.125],
       [0.85 , 0.15 ],
       [0.85 , 0.15 ],
       [0.375, 0.625],
       [0.875, 0.125],
       [0.925, 0.075],
       [0.85 , 0.15 ],
       [0.875, 0.125],
       [0.9  , 0.1  ],
       [0.825, 0.175],
       [0.9  , 0.1  ],
       [0.425, 0.575],
       [0.8  , 0.2  ],
       [0.8  , 0.2  ],
       [0.475, 0.525],
       [0.8  , 0.2  ],
       [0.85 , 0.15 ],
       [0.8  , 0.2  ],
       [0.875, 0.125],
       [0.8  , 0.2  ],
       [0.5  , 0.5  ],
       [0.85 , 0.15 ],
       [0.75 , 0.25 ],
       [0.5

In [109]:
gscv.classes_

array([1, 2], dtype=int64)

In [112]:
cv = cross_validate(model_knn, x, y, cv=10, scoring='roc_auc', return_train_score=True)

In [114]:
cv['test_score'].mean()

0.6182751427316645

In [127]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
import numpy as np

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, stratify=y, random_state=21)
model_tree = DecisionTreeClassifier()
model_tree.fit(x_train, y_train)
y_pred = model_tree.predict(x)

In [128]:
from sklearn.model_selection import cross_val_score
acc_Tree = cross_val_score(model_tree, x_train, y_train, cv=10, scoring='roc_auc').mean()
acc_Tree

0.592594537815126

In [119]:
gscv.best_params_

{'n_neighbors': 40, 'weights': 'uniform'}

In [120]:
gscv.best_score_

0.7151062091503269

In [104]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, stratify=y, random_state=21)
model = KNeighborsClassifier()
param_grid = {
    'n_neighbors' : np.arange(5,50),
    'weights' : ['distance','uniform']
}
rscv = RandomizedSearchCV(model, param_grid, cv=5, scoring='roc_auc', n_iter=20)
rscv.fit(x,y)

RandomizedSearchCV(cv=5, estimator=KNeighborsClassifier(), n_iter=20,
                   param_distributions={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                                        'weights': ['distance', 'uniform']},
                   scoring='roc_auc')

In [105]:
rscv.best_params_

{'weights': 'uniform', 'n_neighbors': 48}

In [106]:
rscv.best_score_

0.7080147058823529

In [107]:
rscv.predict_proba(x_test)

array([[0.72916667, 0.27083333],
       [0.75      , 0.25      ],
       [0.70833333, 0.29166667],
       [0.52083333, 0.47916667],
       [0.6875    , 0.3125    ],
       [0.79166667, 0.20833333],
       [0.83333333, 0.16666667],
       [0.8125    , 0.1875    ],
       [0.77083333, 0.22916667],
       [0.6875    , 0.3125    ],
       [0.41666667, 0.58333333],
       [0.875     , 0.125     ],
       [0.75      , 0.25      ],
       [0.8125    , 0.1875    ],
       [0.85416667, 0.14583333],
       [0.875     , 0.125     ],
       [0.77083333, 0.22916667],
       [0.75      , 0.25      ],
       [0.79166667, 0.20833333],
       [0.52083333, 0.47916667],
       [0.89583333, 0.10416667],
       [0.85416667, 0.14583333],
       [0.83333333, 0.16666667],
       [0.39583333, 0.60416667],
       [0.83333333, 0.16666667],
       [0.875     , 0.125     ],
       [0.83333333, 0.16666667],
       [0.85416667, 0.14583333],
       [0.85416667, 0.14583333],
       [0.85416667, 0.14583333],
       [0.